/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import conexao.ControleProduto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Produto;
import modelo.exceptions.NotExistsException;

/**
 *
 * @author User
 */
public class PrincipalFrame extends javax.swing.JFrame {

     ControleProduto controle = new ControleProduto(); 
     List<Produto> produto = new ArrayList<>(); 
     
    public PrincipalFrame() throws SQLException {
        initComponents(); 
        try{
        produto = controle.getListaProduto();
        atualizarTabela(); 
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "ERRO DE CONEXAO");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProduto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        botExcluir = new javax.swing.JButton();
        botEditar = new javax.swing.JButton();
        botVisualizar = new javax.swing.JButton();
        botInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mercado do zé");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Preço(R$) ", "Total(R$)"
            }
        ));
        jScrollPane1.setViewportView(tabProduto);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        botExcluir.setText("Excluir");
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(botExcluir);

        botEditar.setText("Editar");
        botEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEditarActionPerformed(evt);
            }
        });
        jPanel3.add(botEditar);

        botVisualizar.setText("Visualizar");
        botVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVisualizarActionPerformed(evt);
            }
        });
        jPanel3.add(botVisualizar);

        botInserir.setText("Inserir");
        botInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botInserirActionPerformed(evt);
            }
        });
        jPanel3.add(botInserir);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botInserirActionPerformed
            
            ProdutoDialog telaAuxiliar = new ProdutoDialog(this, true); 
            telaAuxiliar.setVisible(true);
            Produto p; 
            if(telaAuxiliar.getSalvou()){
               p = telaAuxiliar.getProduto(); 
                try {
                    controle.adicionarProduto(p);
                    produto = controle.getListaProduto(); 
                    atualizarTabela(); 
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "ERRO NA CONEXAO!!");
                }
               
            }
            
            
    }//GEN-LAST:event_botInserirActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        int linha = tabProduto.getSelectedRow(); 
        
        if(linha!=-1){
            try {
                controle.deletarProduto(produto.get(linha).getCodigo());
                produto = controle.getListaProduto();
                atualizarTabela(); 
                
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(this, "ERRO NO BANCO DE DADOS");
            } catch (NotExistsException ex) {
                JOptionPane.showMessageDialog(this, "ERRO - PRODUTO NAO IDENTIFICADO"); 
            }
        }
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEditarActionPerformed
         int linha = tabProduto.getSelectedRow();
        if (linha != -1) {
            ProdutoDialog tela = new ProdutoDialog(this, true);

            tela.setProduto(produto.get(linha));
            tela.setVisible(true);

            try {
                controle.alterarProduto(tela.getProduto());
                produto = controle.getListaProduto();
                atualizarTabela();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                        "Erro no SQL");
            } catch (NotExistsException ex) {
                JOptionPane.showMessageDialog(this,
                        "Esse codigo não existe");
            }

        }
        
        
    }//GEN-LAST:event_botEditarActionPerformed

    private void botVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVisualizarActionPerformed
        int linha = tabProduto.getSelectedRow(); 
        ProdutoDialog tela = new ProdutoDialog(this, true); 
        if(linha!=-1){
            tela.setProduto(produto.get(linha));
            tela.setVisible(true);
        }
    }//GEN-LAST:event_botVisualizarActionPerformed

    public void atualizarTabela() throws SQLException{
        DefaultTableModel tabela = (DefaultTableModel) tabProduto.getModel(); 
        
        tabela.setRowCount(0);
        produto = controle.getListaProduto();
        for(Produto p: produto){
            tabela.addRow(new Object[]{p.getCodigo(), p.getNome(), p.getQuantidade(), p.getPreco(), p.getTotal()}); 
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrincipalFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botEditar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JButton botInserir;
    private javax.swing.JButton botVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabProduto;
    // End of variables declaration//GEN-END:variables
}
